name: First-Workflow
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Run all command in one line
              run: |
                echo "First Github Actions"
                ls -ltra
                cat README.md
            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Run for Cover, I am a Dragon..RAWR">>dragon.txt