name: Generate ASCII ARTWORK
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            
            - name: Install cawsay
              run: sudo apt-get install cowsay -y

            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Run for Cover, I am a Dragon..RAWR">>dragon.txt
            - name: Test file
              run: grep -i "dragon" dragon.txt
            - name : Show dragon.txt
              run: cat dragon.txt
            - name: List the Files
              run: ls -ltr